name: 'Publish Tests Report'
description: 'Generates a report for tests results in TRX format'
inputs:
  trx_filter:
    required: false
    type: string
    default: './TestResults/*.trx'
  check_name:
    required: false
    type: string
    default: 'Test Results'
  github-token:
    default: ${{ github.token }}
runs:
  using: "composite"
  steps:
    - name: Test Results
      uses: dorny/test-reporter@v1
      id: test-report
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: ${{ inputs.check_name }}
        path: ${{ inputs.trx_filter }}
        reporter: dotnet-trx

    - name: Prepare results for comment
      id: test-report-extra
      if: success() || failure()    # run this step even if previous step failed
      env:
          TIME_MS: ${{ steps.test-report.outputs.time }}
          PASSED: ${{ steps.test-report.outputs.passed }}
          FAILED: ${{ steps.test-report.outputs.failed }}
          SKIPPED: ${{ steps.test-report.outputs.skipped }}
      run: |
        echo ::set-output name=total::$(($PASSED + $FAILED + $SKIPPED))
        echo ::set-output name=time_s::$(($TIME_MS / 1000))
      shell: bash

    - name: Comment PR
      uses: Beakyn/gha-comment-pull-request@v1.0.2
      if: success() || failure()    # run this step even if previous step failed
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      with:
        comment-message: |
          ### Conclusion: `${{ steps.test-report.outputs.conclusion }}`
          ${{ steps.test-report-extra.outputs.time_s }}s [:stopwatch:](## "duration of all tests")
          ${{ steps.test-report-extra.outputs.total }} tests ${{ steps.test-report.outputs.passed }} [:heavy_check_mark:](## "passed tests") ${{ steps.test-report.outputs.skipped }} [:zzz:](## "skipped / disabled tests") ${{ steps.test-report.outputs.failed }} [:x:](## "failed tests")

          ---

          Results for commit ${{ github.sha }}.
          For more details on these failures, see [this check](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}).

        delete-previous-comment: true