on:
  workflow_call:
    inputs:
      solution_path:
        required: true
        type: string
      dotnet_version:
        required: false
        type: string
        default: 3.1.x
      build_config:
        required: false
        type: string
        default: Release
      dotnet_build_args:
        required: false
        type: string
      dotnet_test_args:
        required: false
        type: string

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build and Test
      uses: trax-retail/.github/.github/actions/dotnet-build-test@1.6
      with:
        solution_path: ${{ inputs.solution_path }}
        dotnet_version: ${{ inputs.dotnet_version }}
        build_config: ${{ inputs.build_config }}
        dotnet_build_args: ${{ inputs.dotnet_build_args }}
        dotnet_test_args: ${{ inputs.dotnet_test_args }}
      continue-on-error: true

    - name: Publish Unit Test Results
      uses: trax-retail/.github/.github/actions/publish-tests-report@1.6
