on:
  workflow_call:
    inputs:
      solution_path:
        required: true
        type: string
      dotnet_version:
        required: false
        type: string
        default: 3.1.x
      build_config:
        required: false
        type: string
        default: Release
      restore_dotnet_tools:
        required: false
        type: boolean
      test_results_directory:
        required: false
        type: string
        default: ./TestResults
      dotnet_build_args:
        required: false
        type: string
      dotnet_test_args:
        required: false
        type: string

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build and Test
      uses: trax-retail/.github/.github/actions/dotnet-build-test@1.7
      with:
        solution_path: ${{ inputs.solution_path }}
        dotnet_version: ${{ inputs.dotnet_version }}
        build_config: ${{ inputs.build_config }}
        restore_dotnet_tools: ${{ inputs.restore_dotnet_tools }}
        test_results_directory: ${{ inputs.test_results_directory }}
        dotnet_build_args: ${{ inputs.dotnet_build_args }}
        dotnet_test_args: ${{ inputs.dotnet_test_args }}

    - name: Publish Unit Test Results
      uses: trax-retail/.github/.github/actions/publish-tests-report@1.7
      if: success() || failure()    # run this step even if previous step failed
